# Generated by Django 2.1.7 on 2019-04-02 05:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organisasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_organisasi', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='perangkat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perangkat', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='proyek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=255, verbose_name='Nama Proyek')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi Proyek')),
            ],
        ),
        migrations.AddField(
            model_name='organisasi',
            name='id_proyek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analis.proyek'),
        ),
    ]
