# Generated by Django 2.1.7 on 2019-04-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analis', '0003_perangkat_proyek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='nama',
            field=models.CharField(max_length=255, verbose_name='Nama Proyek'),
        ),
    ]
