# Generated by Django 2.2.1 on 2019-05-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analis', '0005_auto_20190409_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perangkat',
            name='proyek',
        ),
        migrations.RemoveField(
            model_name='proyek',
            name='user',
        ),
        migrations.DeleteModel(
            name='organisasi',
        ),
        migrations.DeleteModel(
            name='perangkat',
        ),
        migrations.DeleteModel(
            name='proyek',
        ),
    ]
