# Generated by Django 2.2.1 on 2019-07-31 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analis', '0007_analis_proyek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='analis_proyek',
        ),
    ]
