# Generated by Django 2.1.7 on 2019-04-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='syafiq', max_length=255),
            preserve_default=False,
        ),
    ]
