# Generated by Django 2.2.1 on 2019-07-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Status Aktif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='analis',
            field=models.BooleanField(default=False, verbose_name='Status Analis'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Alamat Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Status Manajer Proyek'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surveyor',
            field=models.BooleanField(default=False, verbose_name='Status Surveyor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Anggota'),
        ),
    ]
