# Generated by Django 2.2.1 on 2019-07-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190713_0301'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loggedinuser',
            table='LoggedInUser',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
