# Generated by Django 2.2.1 on 2019-07-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='anggota_survey',
        ),
    ]
