# Generated by Django 2.2.1 on 2019-07-19 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0020_auto_20190718_2155'),
        ('surveyor', '0002_remove_survey_anggota_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='anggota_survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anggota_survey', to='projectmanajer.anggota_survey', verbose_name='anggota_survey'),
            preserve_default=False,
        ),
    ]
