# Generated by Django 2.2.1 on 2019-07-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0003_survey_anggota_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='anggota_survey',
        ),
    ]
