# Generated by Django 2.2.1 on 2019-07-24 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0006_survey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
    ]
