# Generated by Django 2.2.1 on 2019-07-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0007_remove_survey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='rekap_survey',
        ),
    ]
