# Generated by Django 2.2.1 on 2019-07-26 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0008_remove_survey_rekap_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='anggota_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota_survey', to='projectmanajer.anggota_survey', verbose_name='Organisasi'),
        ),
    ]
