# Generated by Django 2.2.1 on 2019-08-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0009_auto_20190726_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='file',
            field=models.FileField(default=1, upload_to='attachments'),
            preserve_default=False,
        ),
    ]
