# Generated by Django 2.2.1 on 2019-08-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0010_survey_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='file',
        ),
    ]
