# Generated by Django 2.2.1 on 2019-08-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0011_remove_survey_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='file',
            field=models.FileField(default=1, upload_to='attachments'),
            preserve_default=False,
        ),
    ]
