# Generated by Django 2.2.4 on 2019-08-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0012_survey_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='file',
        ),
        migrations.CreateModel(
            name='lampiran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='surveyor.survey')),
            ],
        ),
    ]
