# Generated by Django 2.2.1 on 2019-05-25 16:04

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='proyek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Proyek')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi Proyek')),
                ('pjProyek', models.CharField(max_length=255, verbose_name='PJ Proyek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proyek',
            },
        ),
        migrations.CreateModel(
            name='perangkat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perangkat', django.contrib.postgres.fields.jsonb.JSONField()),
                ('penanggung_jawab', models.CharField(max_length=50, verbose_name='Nama Penanggung Jawab')),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perangkat', to='projectmanajer.proyek')),
            ],
            options={
                'db_table': 'perangkat',
            },
        ),
        migrations.CreateModel(
            name='organisasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_organisasi', models.CharField(blank=True, max_length=255)),
                ('narasumber', models.CharField(max_length=50, verbose_name='Narasumber')),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisasi', to='projectmanajer.proyek')),
            ],
            options={
                'db_table': 'organisasi',
            },
        ),
    ]
