# Generated by Django 2.2.1 on 2019-05-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0002_auto_20190526_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisasi',
            name='narasumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Narasumber'),
        ),
    ]
