# Generated by Django 2.2.1 on 2019-05-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0003_auto_20190526_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisasi',
            old_name='proyek',
            new_name='proyek_id',
        ),
        migrations.RenameField(
            model_name='perangkat',
            old_name='proyek',
            new_name='proyek_id',
        ),
    ]
