# Generated by Django 2.2.1 on 2019-05-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0004_auto_20190529_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisasi',
            old_name='proyek_id',
            new_name='proyek',
        ),
        migrations.RenameField(
            model_name='perangkat',
            old_name='proyek_id',
            new_name='proyek',
        ),
    ]
