# Generated by Django 2.2.1 on 2019-06-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0005_auto_20190529_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='pjProyek',
            field=models.CharField(max_length=255, verbose_name='Penanggung Jawav Proyek'),
        ),
    ]
