# Generated by Django 2.2.1 on 2019-06-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0008_auto_20190613_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perangkat',
            name='proyek',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perangkat', to='projectmanajer.proyek'),
        ),
    ]
