# Generated by Django 2.2.1 on 2019-06-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0009_auto_20190617_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perangkat',
            name='perangkat',
            field=models.TextField(),
        ),
    ]
