# Generated by Django 2.2.1 on 2019-06-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0011_auto_20190623_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perangkat',
            name='perangkat',
            field=models.TextField(),
        ),
    ]
