# Generated by Django 2.2.1 on 2019-07-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0013_auto_20190623_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='perangkat',
            name='nama_perangkat',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
