# Generated by Django 2.2.1 on 2019-07-13 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanajer', '0014_perangkat_nama_perangkat'),
    ]

    operations = [
        migrations.CreateModel(
            name='anggota_survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anggota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('survey_organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisasi', to='projectmanajer.organisasi')),
            ],
        ),
    ]
