# Generated by Django 2.2.1 on 2019-07-13 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0015_anggota_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota_survey',
            name='anggota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL, verbose_name='Surveyor'),
        ),
        migrations.AlterField(
            model_name='anggota_survey',
            name='survey_organisasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisasi', to='projectmanajer.organisasi', verbose_name='Organisasi'),
        ),
    ]
