# Generated by Django 2.2.1 on 2019-07-15 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0016_auto_20190713_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota_survey',
            name='anggota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL, verbose_name='Surveyor'),
        ),
    ]
