# Generated by Django 2.2.1 on 2019-07-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0017_auto_20190715_0717'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anggota_survey',
            table='anggota_survey',
        ),
    ]
