# Generated by Django 2.2.1 on 2019-07-18 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0018_auto_20190716_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota_survey',
            name='proyek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyek', to='projectmanajer.proyek', verbose_name='proyek'),
        ),
        migrations.AlterModelTable(
            name='proyek',
            table=None,
        ),
    ]
