# Generated by Django 2.2.1 on 2019-07-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0019_auto_20190718_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota_survey',
            name='proyek',
        ),
        migrations.AlterModelTable(
            name='proyek',
            table='proyek',
        ),
    ]
