# Generated by Django 2.2.1 on 2019-07-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanajer', '0022_auto_20190727_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota_survey',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sudah Melakukan Survey'), (0, 'Belum Melakukan Survey')], default=0),
        ),
    ]
