# Generated by Django 2.2.1 on 2019-07-31 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanajer', '0023_auto_20190727_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='analis_proyek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Analis')),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyek', to='projectmanajer.proyek', verbose_name='Proyek')),
            ],
            options={
                'db_table': 'analis_proyek',
            },
        ),
    ]
